apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 472937934169.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 472937934169.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 9407c26a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
